// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'pref-auto-set'
  | 'pref-batch-complete'
  | 'pref-batch-no-language'
  | 'pref-batch-progress'
  | 'pref-batch-progress-detail'
  | 'pref-batch-running'
  | 'pref-batch-section'
  | 'pref-batch-set-button'
  | 'pref-custom-language'
  | 'pref-help'
  | 'pref-language-label'
  | 'pref-overwrite'
  | 'pref-title'
  | 'prefs-title'
  | 'startup-begin'
  | 'startup-finish';
