// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "targetLanguage": string;
      "autoSetOnImport": boolean;
      "overwriteExisting": boolean;
    };
  }
}
